### ISSUE TITLE
Choisir le nom du site (et de la boite...).

### ISSUE THREAD

**Issue by jeanbaptisteassouad** [ArtemisMucaj/gearbox-website#17]

**Comment by jeanbaptisteassouad** [comment]
pamplemousse

**Comment by jeanbaptisteassouad** [comment]
Super site pour avoir des combinaisons de noms et voir si ils ont libres : http://www.panabee.com/

**Comment by jeanbaptisteassouad** [comment]
pample :)

**Comment by ArtemisMucaj** [comment]
pachanical

**Comment by jeanbaptisteassouad** [comment]
SultanICal

**Comment by jeanbaptisteassouad** [comment]
https://en.wikipedia.org/wiki/Domain_hack

On peut faire du hack ! :)

**Comment by jeanbaptisteassouad** [comment]
KataLog

**Comment by jeanbaptisteassouad** [comment]
nearHouse

**Comment by jeanbaptisteassouad** [comment]
pampleHouse
thePampleHouse

**Comment by jeanbaptisteassouad** [comment]
Un super site pour vérifier la disponibilité du nom de domaine : https://domaintyper.com/

**Comment by jeanbaptisteassouad** [comment]
Operator

**Comment by jeanbaptisteassouad** [comment]
TheFactory

**Comment by jeanbaptisteassouad** [comment]
facts

**Comment by jeanbaptisteassouad** [comment]
fact sheet

**Comment by jeanbaptisteassouad** [comment]
Part  Ition

**Comment by jeanbaptisteassouad** [comment]
Bilan :

pamplemousse
pample
pachanical
SultanICal
KataLog
nearHouse
pampleHouse
thePampleHouse
Operator
TheFactory
facts
fact sheet
Factsminer
Part Ition

**Comment by jeanbaptisteassouad** [comment]
The choice : http://thef.ac/tory
